SERF
block-core/blockcore pull request #326
Opened 2021-04-05 02:24 UTC by cryptoeejit

The amazing SERF community coin.

2021-04-05 13:16 UTC, sondreb requested changes

2021-04-05 13:16 UTC, sondreb commented on src/Networks/Blockcore.Networks.SERF/Networks/Deployments/SERFBIP9Deployments.cs
> +               flags.ScriptFlags |= ScriptVerify.CheckColdStakeVerify;
Don't need the append flag here, can simply be =

2021-04-05 13:16 UTC, sondreb commented on src/Networks/Blockcore.Networks.SERF/Networks/Deployments/SERFBIP9Deployments.cs
> +      public const int TestDummy = 0;
Remove the dummy and reorganize the indexes of deployments.

2021-04-05 13:16 UTC, sondreb commented on src/Networks/Blockcore.Networks.SERF/Networks/Deployments/SERFBIP9Deployments.cs
> +      public const int NumberOfDeployments = 4;
Make this 3 when you remove the dummy

2021-04-05 13:16 UTC, sondreb commented on src/Networks/Blockcore.Networks.SERF/Networks/SERFRegTest.cs
> +             bip9Deployments: new NoBIP9Deployments(),
You should consider copying the same configuration from main.

2021-04-05 13:16 UTC, sondreb commented on src/Networks/Blockcore.Networks.SERF/SERFSetup.cs
> +         PoSVersion = 3
You should consider going with POSv4 right away

2021-04-06 10:29 UTC, cryptoeejit commented
Thanks.  Will get to it.

2021-04-07 11:50 UTC, closed without merging

2021-04-07 11:57 UTC, cryptoeejit commented
Think I need to review the setup more,  Hopefully resubmit when its better,