Cache the deployment flags to improve startup
block-core/blockcore pull request #340
Opened 2021-05-18 11:58 UTC by sondreb

- The deployment flags are cached when calculated as new blocks come in.
- The deployment flags are read from cache at startup, as they cannot have changed since shutdown.
- This gives a very big improvement on node startup.
- #337

2021-05-18 21:04 UTC, dangershony commented on src/Features/Blockcore.Features.Consensus/Rules/CommonRules/SetActivationDeploymentsPartialValidationRule.cs
> +            if (this.keyValueRepository != null)
hmm I am not sure this is a good idea, this means we push to disk on each block arriving.
It's not such a good idea to push to disk in the rules in general, perhaps this should be done on shutdown however then we need to check for crashes (check the node deployment current height is the same as the chained header.

I think we can persist to disk at the same time we persist the chained headers in the base feature (this happens every few min).

2021-05-18 21:05 UTC, dangershony requested changes
This is a good idea but we should move the persist to the base feature

2021-05-19 09:52 UTC, dangershony commented
> Yes, agree and that was initial thought. Though we likely should cache it in-memory then, so we don't need to calculate the flags on shutdown.  

I think its already cached in the component

2021-06-09 16:26 UTC, sondreb commented
> Does this prevent from loading it on startup though?

Yes, it loads pre-calculated on startup, from the key-value store. We never need to re-calculate from genesis on secondary launches of the software.

2021-07-04 16:51 UTC, merged